language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3
install:
  - pip install coverage coveralls zope.testrunner
  - pip install -e .[test]
script:
  - coverage run -m zope.testrunner --test-path=src -v
after_success:
  - coveralls
notifications:
  email: false
cache: pip
